version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ~/.kaggle:/root/.kaggle
      - ./kaggle-env:/app/kaggle-env
    depends_on:
      - kaggle-service

  kaggle-service:
    build:
      context: .
      dockerfile: Dockerfile.kaggle
    volumes:
      - ~/.kaggle:/root/.kaggle
      - ./kaggle-env:/app/kaggle-env
    environment:
      - KAGGLE_USERNAME=${KAGGLE_USERNAME}
      - KAGGLE_KEY=${KAGGLE_KEY}
    command: sh -c "python -m venv /app/kaggle-env && /app/kaggle-env/bin/pip install -r requirements.txt && tail -f /dev/null" 