version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ~/.kaggle:/root/.kaggle  # Mount Kaggle credentials
    environment:
      - NODE_ENV=development
      - PATH=/opt/kaggle-env/bin:${PATH}
      - VIRTUAL_ENV=/opt/kaggle-env
    command: >
      bash -c "
        chmod 600 /root/.kaggle/kaggle.json &&
        npm install &&
        npm run start:dev
      " 