version: '3'

services:
  app:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules  # This prevents the host node_modules from mounting over container node_modules
      - ~/.kaggle:/root/.kaggle  # Mount Kaggle credentials
    environment:
      - NODE_ENV=development
      - PATH=/opt/kaggle-env/bin:${PATH}
      - VIRTUAL_ENV=/opt/kaggle-env
    command: >
      bash -c "
        chmod 600 /root/.kaggle/kaggle.json &&
        npm run start:dev
      "
    # Add healthcheck to ensure the service is running properly
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s 