version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  kaggle-service:
    build:
      context: .
      dockerfile: Dockerfile.kaggle
    volumes:
      - ~/.kaggle:/root/.kaggle
    environment:
      - KAGGLE_USERNAME=${KAGGLE_USERNAME}
      - KAGGLE_KEY=${KAGGLE_KEY}
    command: tail -f /dev/null # Keeps container running 